"""Application use cases and orchestration."""

from app.application.curriculum import Curriculum, CurriculumGenerator
from app.application.errors import CurriculumGenerationError
from app.application.models import (
    AttemptResult,
    CorrectAttemptCommand,
    CreateGoalCommand,
    DueReview,
    GradeAnswerCommand,
    LearningInsights,
    PersistPlanProposalCommand,
    PlanDetails,
    ProposedKnowledgeEdge,
    ProposedKnowledgeNode,
    ProposedPlanItem,
    ResourceSnippet,
    SessionDetails,
    StartReviewSessionCommand,
    StartSessionCommand,
    SubmitAttemptCommand,
)
from app.application.services import (
    ApplicationDependencies,
    CompleteStudySession,
    CorrectExerciseAttempt,
    CreateLearningGoal,
    CreateRemediationExercise,
    CreateStudyPlan,
    DeferReview,
    ExportLearningData,
    GetAdaptiveRecommendation,
    GetDueReviews,
    GetLearningGoal,
    GetLearningInsights,
    GetMasteryState,
    GetStudyPlan,
    GetStudySession,
    GradeObjectiveAnswer,
    ListLearningGoals,
    PersistStudyPlanProposal,
    SearchLearningResources,
    StartReviewSession,
    StartStudySession,
    SubmitExerciseAttempt,
)
from app.application.templates import FixedCurriculumGenerator

__all__ = [
    "ApplicationDependencies",
    "AttemptResult",
    "CompleteStudySession",
    "CorrectAttemptCommand",
    "CorrectExerciseAttempt",
    "CreateGoalCommand",
    "CreateLearningGoal",
    "CreateRemediationExercise",
    "CreateStudyPlan",
    "DeferReview",
    "Curriculum",
    "CurriculumGenerationError",
    "CurriculumGenerator",
    "DueReview",
    "ExportLearningData",
    "FixedCurriculumGenerator",
    "GetDueReviews",
    "GetAdaptiveRecommendation",
    "GetLearningGoal",
    "GetLearningInsights",
    "GetMasteryState",
    "GetStudyPlan",
    "GetStudySession",
    "GradeAnswerCommand",
    "GradeObjectiveAnswer",
    "LearningInsights",
    "ListLearningGoals",
    "PersistPlanProposalCommand",
    "PersistStudyPlanProposal",
    "PlanDetails",
    "ProposedKnowledgeEdge",
    "ProposedKnowledgeNode",
    "ProposedPlanItem",
    "ResourceSnippet",
    "SearchLearningResources",
    "SessionDetails",
    "StartSessionCommand",
    "StartReviewSessionCommand",
    "StartReviewSession",
    "StartStudySession",
    "SubmitAttemptCommand",
    "SubmitExerciseAttempt",
]
